#!/usr/bin/env bash
# AMINRA full-system customer-ready QA runner.
# Purpose: execute every available automated/runtime/browser QA gate across AMINRA risk domains,
#          while keeping deferred/blocked gaps explicit. SMTP is skipped by default.
# Usage:
#   cd /home/user/Documents/aminra-docker-system
#   bash scripts/qa/run-customer-ready-full-system-qa.sh
# Optional:
#   RUN_LOAD=1 RUN_FULL_E2E=1 bash scripts/qa/run-customer-ready-full-system-qa.sh
#   RUN_CHAOS=1 CHAOS_APPROVED=true bash scripts/qa/run-customer-ready-full-system-qa.sh

set -uo pipefail

ROOT_DIR="${AMINRA_ROOT:-/home/user/Documents/aminra-docker-system}"
cd "$ROOT_DIR" || exit 2

RUN_ID="${RUN_ID:-$(date +%Y-%m-%d-customer-ready-full-system)}"
OUT_DIR="${OUT_DIR:-docs/qa/${RUN_ID}}"
TERM_DIR="$OUT_DIR/evidence/terminal"
RAW_DIR="$OUT_DIR/evidence/raw"
SCREEN_DIR="$OUT_DIR/evidence/screenshots"
STATUS_FILE="$OUT_DIR/status.tsv"
REPORT_FILE="$OUT_DIR/report.md"

mkdir -p "$TERM_DIR" "$RAW_DIR" "$SCREEN_DIR"
: > "$STATUS_FILE"

# Load gitignored QA credentials if present. Do not print values.
if [[ -f ".qa/aminra-demo-credentials.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source .qa/aminra-demo-credentials.env
  set +a
fi

RUN_SMTP="${RUN_SMTP:-0}"
RUN_LOAD="${RUN_LOAD:-0}"
RUN_CHAOS="${RUN_CHAOS:-0}"
RUN_VISUAL="${RUN_VISUAL:-0}"
RUN_FULL_E2E="${RUN_FULL_E2E:-0}"
CHAOS_APPROVED="${CHAOS_APPROVED:-false}"

step_no=0
fail_count=0
warn_count=0
blocked_count=0
pass_count=0

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-//; s/-$//'
}

record_status() {
  local domain="$1" status="$2" name="$3" evidence="$4" note="${5:-}"
  printf '%s\t%s\t%s\t%s\t%s\n' "$domain" "$status" "$name" "$evidence" "$note" >> "$STATUS_FILE"
  case "$status" in
    PASS) pass_count=$((pass_count+1)) ;;
    FAIL) fail_count=$((fail_count+1)) ;;
    WARN) warn_count=$((warn_count+1)) ;;
    BLOCKED|DEFERRED) blocked_count=$((blocked_count+1)) ;;
  esac
}

run_step() {
  local domain="$1" name="$2" cmd="$3"
  step_no=$((step_no+1))
  local slug
  slug="$(printf '%03d-%s' "$step_no" "$(slugify "$domain-$name")")"
  local log="$TERM_DIR/${slug}.txt"
  {
    echo "# Domain: $domain"
    echo "# Step: $name"
    echo "# Started: $(date -Is)"
    echo "# Command: $cmd"
    echo
  } > "$log"
  echo "[$(date +%H:%M:%S)] RUN $domain :: $name"
  # Run in a subshell so `cd frontend/...` inside a step cannot leak into later steps,
  # while still allowing helper functions such as sync_backend_test_assets.
  # Commands are generated by this trusted QA runner, not by user input.
  ( eval "$cmd" ) >> "$log" 2>&1
  local ec=$?
  {
    echo
    echo "# Finished: $(date -Is)"
    echo "# Exit code: $ec"
  } >> "$log"
  if [[ $ec -eq 0 ]]; then
    record_status "$domain" "PASS" "$name" "$log" ""
  else
    record_status "$domain" "FAIL" "$name" "$log" "exit_code=$ec"
  fi
  return 0
}

mark_deferred() {
  local domain="$1" name="$2" note="$3"
  step_no=$((step_no+1))
  local log="$TERM_DIR/$(printf '%03d-%s' "$step_no" "$(slugify "$domain-$name-deferred")").txt"
  {
    echo "# Domain: $domain"
    echo "# Step: $name"
    echo "# Status: DEFERRED"
    echo "# Note: $note"
    echo "# Time: $(date -Is)"
  } > "$log"
  record_status "$domain" "DEFERRED" "$name" "$log" "$note"
}

mark_blocked() {
  local domain="$1" name="$2" note="$3"
  step_no=$((step_no+1))
  local log="$TERM_DIR/$(printf '%03d-%s' "$step_no" "$(slugify "$domain-$name-blocked")").txt"
  {
    echo "# Domain: $domain"
    echo "# Step: $name"
    echo "# Status: BLOCKED"
    echo "# Note: $note"
    echo "# Time: $(date -Is)"
  } > "$log"
  record_status "$domain" "BLOCKED" "$name" "$log" "$note"
}

sync_backend_test_assets() {
  # The running backend image may not contain host-side test files/scripts.
  # Sync read-only QA assets into the live container before pytest/fixture steps.
  local cid
  cid="$(docker compose ps -q aminra-backend 2>/dev/null || true)"
  if [[ -z "$cid" ]]; then
    echo "BLOCKED: aminra-backend container not found" >&2
    return 1
  fi
  docker cp backend/tests/. "$cid":/app/tests >/dev/null
  docker compose exec -T aminra-backend sh -lc 'mkdir -p /app/scripts/qa' >/dev/null
  if [[ -d scripts/qa ]]; then
    docker cp scripts/qa/. "$cid":/app/scripts/qa >/dev/null
  fi
}

be_pytest() {
  local domain="$1" name="$2" tests="$3"
  run_step "$domain" "$name" "sync_backend_test_assets && docker compose exec -T aminra-backend sh -lc 'cd /app && if [ -f /vault/secrets/env.sh ]; then . /vault/secrets/env.sh; fi; PYTHONPATH=/app pytest -q $tests'"
}

fe_cmd() {
  local domain="$1" name="$2" cmd="$3"
  run_step "$domain" "$name" "cd frontend/aminra-web && $cmd"
}

# 0. Baseline / release boundary
run_step "00-env" "date-and-git-boundary" "date -Is; git branch --show-current; git rev-parse --short HEAD; git status --short; git diff --stat"
run_step "00-env" "docker-compose-health-and-http-smoke" "docker compose ps; echo '--- backend health ---'; curl -fsS http://127.0.0.1:8100/health; echo; echo '--- local FE ---'; curl -I -s http://127.0.0.1:3100 | head -12; echo '--- public FE ---'; curl -I -s https://dev-web.silvergem.org | head -12"
run_step "00-env" "runtime-smoke-script" "bash scripts/qa/runtime-smoke.sh"
run_step "00-env" "diff-whitespace-check" "git diff --check"

# 1. Auth / Keycloak / session / RBAC
be_pytest "01-auth-session-rbac" "keycloak-token-admin-jwks-dual-auth" "tests/test_keycloak_token_security.py tests/test_keycloak_admin_edge.py tests/test_keycloak_jwks_edge.py tests/test_dual_auth_unit.py tests/test_dual_auth_fast_path.py tests/test_dual_auth_cross_tenant_unit.py"
be_pytest "01-auth-session-rbac" "role-boundaries-live-and-admin-reset" "tests/test_role_boundaries_live_smoke.py tests/test_admin_user_password_reset.py tests/test_demo_account_login_smoke_script.py"
fe_cmd "01-auth-session-rbac" "frontend-auth-focused-vitest" "npm test -- --run __tests__/admin-auth-route-boundary.test.tsx __tests__/auth-cache-behavior.test.tsx __tests__/admin-password-self-reset.test.tsx"
fe_cmd "01-auth-session-rbac" "playwright-keycloak-token-login-multiuser" "npx playwright test e2e/keycloak/01-token-validation.spec.ts e2e/keycloak/02-login-ui-flow.spec.ts e2e/keycloak/03-attacker-scenarios.spec.ts e2e/keycloak/04-multi-user.spec.ts --project=desktop-chromium"
fe_cmd "01-auth-session-rbac" "playwright-token-isolation-and-logout" "npx playwright test e2e/22-token-isolation.spec.ts e2e/23-cross-context-logout.spec.ts --project=desktop-chromium"

if [[ "$RUN_SMTP" == "1" ]]; then
  run_step "01-auth-session-rbac" "smtp-keycloak-email-check" "make keycloak-email-check"
else
  mark_deferred "01-auth-session-rbac" "smtp-verifyEmail-password-reset-live-send" "Founder explicitly deferred SMTP. Keep customer_onboarding/production_go non-PASS until RUN_SMTP=1 and live-send passes."
fi

# 2. Tenant isolation / IDOR / route boundary
be_pytest "02-tenant-idor-route-boundary" "cross-tenant-and-unauth-boundaries" "tests/test_keycloak_cross_tenant_attack.py tests/test_dual_auth_cross_tenant_unit.py tests/test_unauth_route_boundaries.py tests/test_certificate_pdf_integrity_smoke.py tests/test_generate_document_export_security.py tests/test_kc_sub_fk_smoke.py tests/uat/test_uat_c_tenant_isolation.py"
run_step "02-tenant-idor-route-boundary" "route-inventory-unknown-risk-scan" "python3 - <<'PY'
from pathlib import Path
p=Path('docs/qa/route-auth-tenant-inventory.md')
text=p.read_text() if p.exists() else ''
print('public_unknown_count=', text.count('auth signal: public/unknown'))
print('tenant_unknown_count=', text.count('tenant note: unknown'))
print('NOTE: counts > 0 require executable negative tests before production GO')
PY"

# 3. Supply chain public trace / sealed snapshot
be_pytest "03-supply-chain-trace" "supply-chain-core-sealing-eligibility" "tests/test_supply_chain_sealing.py tests/test_supply_chain_batches.py tests/test_supply_chain_suppliers.py tests/test_supply_chain_materials.py tests/test_supply_chain_processes.py tests/test_supply_chain_supplier_eligibility_routes.py tests/test_supplier_eligibility_service.py tests/test_migrations_supplier_eligibility.py"
run_step "03-supply-chain-trace" "seed-deterministic-public-trace-fixture" "sync_backend_test_assets && docker compose exec -T aminra-backend sh -lc 'cd /app && if [ -f /vault/secrets/env.sh ]; then . /vault/secrets/env.sh; fi; python scripts/qa/seed-public-trace-fixture.py'"
run_step "03-supply-chain-trace" "public-trace-valid-invalid-smoke" "python3 - <<'PY'
import json, re, subprocess, sys, pathlib, urllib.request
term=pathlib.Path('$TERM_DIR')
ids=[]
for f in term.glob('*seed-deterministic-public-trace-fixture*.txt'):
    ids += re.findall(r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}', f.read_text(errors='ignore'))
if not ids:
    print('BLOCKED: no public_trace_id found in seed output')
    sys.exit(2)
trace_id=ids[0]
print('trace_id=', trace_id)
for url, expect in [
    (f'http://127.0.0.1:8100/api/supply-chain/batches/trace/{trace_id}', 200),
    (f'https://dev-web.silvergem.org/api/api/supply-chain/batches/trace/{trace_id}', 200),
    ('https://dev-web.silvergem.org/api/api/supply-chain/batches/trace/ABC123', 404),
    ('https://dev-web.silvergem.org/api/api/supply-chain/batches/trace/%27%20OR%201%3D1--', 404),
]:
    cp=subprocess.run(['curl','-sS','-o','/tmp/aminra-trace-smoke.json','-w','%{http_code}',url], text=True, capture_output=True, timeout=20)
    code=int(cp.stdout.strip() or '0')
    print(url, '->', code, 'expected', expect)
    if code != expect:
        sys.exit(1)
    body=pathlib.Path('/tmp/aminra-trace-smoke.json').read_text(errors='ignore')
    forbidden=['tenant_id','provider_id','source_certificate_id','changed_by']
    if code==200 and any(x in body for x in forbidden):
        print('PRIVATE_FIELD_LEAK', [x for x in forbidden if x in body])
        sys.exit(1)
PY"
fe_cmd "03-supply-chain-trace" "playwright-supply-chain-and-demo-spine" "npx playwright test e2e/10-supply-chain.spec.ts e2e/33-batch1-workflow-integrity.spec.ts e2e/40-supply-chain-create-contracts.spec.ts e2e/38-demo-spine-keycloak.spec.ts --project=desktop-chromium"

# 4. Submission / certification lifecycle
be_pytest "04-submission-cert-lifecycle" "submission-revisions-sla-and-cert-lifecycle" "tests/test_submission_revisions_unit.py tests/test_submission_revisions_integration.py tests/test_submission_sla_unit.py tests/test_submission_sla_integration.py tests/uat/test_uat_a_cert_lifecycle.py tests/uat/test_uat_d_cert_verify_recall.py tests/test_cert_lifecycle_unit.py tests/test_cert_lifecycle_integration.py tests/test_certificate_pdf_unit.py tests/test_certificate_pdf_integration.py tests/test_certificate_pdf_integrity_smoke.py tests/test_public_verify_blockchain.py"
run_step "04-submission-cert-lifecycle" "known-p0-gap-test-file-presence" "python3 - <<'PY'
from pathlib import Path
missing=[]
for f in ['backend/tests/test_submission_state_machine.py','backend/tests/test_submission_document_lock.py','backend/tests/test_certificate_lifecycle_scope.py','backend/tests/test_certificate_number_concurrency.py']:
    if not Path(f).exists():
        missing.append(f)
if missing:
    print('MISSING_P0_TEST_FILES:')
    print('\n'.join(missing))
    print('These gaps must be implemented or mapped to equivalent existing tests before production GO.')
    raise SystemExit(2)
print('All named P0 lifecycle gap test files exist')
PY"
fe_cmd "04-submission-cert-lifecycle" "playwright-cert-and-state-scoring" "npx playwright test e2e/14-cuj-cert-lifecycle.spec.ts e2e/35-batch5-state-scoring.spec.ts --project=desktop-chromium"

# 5. Admin / users / member / auditor CRUD
be_pytest "05-admin-user-crud" "admin-user-member-auditor-crud" "tests/test_admin_user_password_reset.py tests/test_admin_crud_unit.py tests/test_auth_invite_canonical_invited_by.py tests/test_company_logo_empty_state.py tests/test_kc_sub_fk_smoke.py"
fe_cmd "05-admin-user-crud" "playwright-admin-user-flows" "npx playwright test e2e/05-admin-flow.spec.ts e2e/20-admin-unified-auth.spec.ts e2e/21-admin-pages-token-pattern.spec.ts e2e/30-admin-user-edit-ux.spec.ts --project=desktop-chromium"

# 6. PDF / document rendering / versioning / artifacts
be_pytest "06-pdf-doc-versioning" "pdf-renderer-document-versioning" "tests/integration/test_pdf_full_pipeline.py tests/test_schema_aware_data_unit.py tests/test_pdf_filter_pipeline_unit.py tests/test_pdf_data_aggregator_unit.py tests/test_document_versioning_unit.py tests/test_document_versioning_integration.py tests/test_document_versioning_sec.py tests/test_document_versioning_func.py tests/test_document_versioning_regression.py"
if [[ "$RUN_VISUAL" == "1" ]]; then
  be_pytest "06-pdf-doc-versioning" "pdf-visual-baselines" "tests/visual/test_pdf_baselines.py"
else
  mark_deferred "06-pdf-doc-versioning" "pdf-visual-baselines" "RUN_VISUAL=0. Run with RUN_VISUAL=1 for visual baseline validation."
fi
fe_cmd "06-pdf-doc-versioning" "playwright-template-document-ui" "npx playwright test e2e/27-template-content-integrity.spec.ts e2e/28-admin-template-view.spec.ts e2e/31-revision-panel-visibility.spec.ts e2e/34-batch4-file-llm-safety.spec.ts --project=desktop-chromium"

# 7. Jobs / audit / data rights / upload / rate-limits
be_pytest "07-jobs-audit-data-security" "jobs-audit-data-upload" "tests/test_jobs_unit.py tests/test_jobs_integration.py tests/test_anchor_job_unit.py tests/test_data_export_unit.py tests/test_data_export_integration.py tests/test_data_deletion_unit.py tests/test_data_deletion_integration.py tests/test_audit_log_unit.py tests/test_audit_log_integration.py tests/test_audit_log_coverage.py tests/test_upload_validation.py tests/test_config_tunables.py"
run_step "07-jobs-audit-data-security" "high-signal-log-scan" "docker compose logs --since=60m aminra-backend arq-worker keycloak 2>&1 | grep -Ei 'traceback|exception|error|failed|fatal|database not available|secret|token' || true"
run_step "07-jobs-audit-data-security" "rate-limit-doc-presence" "test -f docs/api/rate-limiting.md && sed -n '1,180p' docs/api/rate-limiting.md"

# 8. Frontend contracts / build / accessibility / browser
fe_cmd "08-frontend-browser-a11y" "frontend-full-vitest" "npm test"
fe_cmd "08-frontend-browser-a11y" "frontend-lint" "npm run lint"
fe_cmd "08-frontend-browser-a11y" "frontend-build" "npm run build"
fe_cmd "08-frontend-browser-a11y" "playwright-accessibility-mobile-critical" "npx playwright test e2e/accessibility.spec.ts e2e/19-mobile-responsive-audit.spec.ts --project=desktop-chromium"
if [[ "$RUN_FULL_E2E" == "1" ]]; then
  fe_cmd "08-frontend-browser-a11y" "playwright-full-matrix" "npx playwright test"
else
  mark_deferred "08-frontend-browser-a11y" "playwright-full-matrix" "RUN_FULL_E2E=0. Focused critical Playwright set ran; full matrix deferred."
fi

# 9. Load / performance / deploy safety / chaos
run_step "09-load-chaos-deploy" "deploy-safety-gates" "bash -n scripts/deploy-from-registry.sh; set +e; DRY_RUN=true scripts/deploy-from-registry.sh >/tmp/aminra-deploy-default.txt 2>&1; ec1=\$?; DEPLOY_STRATEGY=maintenance DEPLOY_WINDOW_APPROVED=true DRY_RUN=true scripts/deploy-from-registry.sh >/tmp/aminra-deploy-maint.txt 2>&1; ec2=\$?; DEPLOY_STRATEGY=rolling DEPLOY_WINDOW_APPROVED=true DRY_RUN=true scripts/deploy-from-registry.sh >/tmp/aminra-deploy-rolling.txt 2>&1; ec3=\$?; set -e; echo default_exit=\$ec1 maintenance_exit=\$ec2 rolling_exit=\$ec3; cat /tmp/aminra-deploy-default.txt /tmp/aminra-deploy-maint.txt /tmp/aminra-deploy-rolling.txt; test \$ec1 -ne 0; test \$ec2 -eq 0; test \$ec3 -ne 0"
if [[ "$RUN_LOAD" == "1" ]]; then
  run_step "09-load-chaos-deploy" "public-trace-load-profile" "python3 - <<'PY'
import concurrent.futures, pathlib, re, statistics, subprocess, time
term=pathlib.Path('$TERM_DIR')
ids=[]
for f in term.glob('*seed-deterministic-public-trace-fixture*.txt'):
    ids += re.findall(r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}', f.read_text(errors='ignore'))
if not ids:
    raise SystemExit('no public_trace_id found')
url=f'https://dev-web.silvergem.org/api/api/supply-chain/batches/trace/{ids[0]}'
def one(_):
    t=time.perf_counter()
    cp=subprocess.run(['curl','-sS','-o','/dev/null','-w','%{http_code}',url], text=True, capture_output=True, timeout=20)
    return (time.perf_counter()-t)*1000, cp.stdout.strip()
with concurrent.futures.ThreadPoolExecutor(max_workers=50) as ex:
    results=list(ex.map(one, range(200)))
lats=[x[0] for x in results]
errs=[x for x in results if x[1] != '200']
p95=statistics.quantiles(lats,n=100)[94]
print({'requests':len(results),'errors':len(errs),'p95_ms':round(p95,1),'target_ms':800})
if errs or p95 >= 800:
    raise SystemExit(1)
PY"
else
  mark_deferred "09-load-chaos-deploy" "public-trace-load-profile" "RUN_LOAD=0. Enable RUN_LOAD=1 to run performance SLO probe."
fi
if [[ "$RUN_CHAOS" == "1" && "$CHAOS_APPROVED" == "true" ]]; then
  run_step "09-load-chaos-deploy" "chaos-approved-placeholder" "echo 'Run the approved chaos drill plan from docs/qa/2026-09-11-production-risk-closure/chaos-drill-plan.md'; test -f docs/qa/2026-09-11-production-risk-closure/chaos-drill-plan.md"
else
  mark_deferred "09-load-chaos-deploy" "chaos-drills" "RUN_CHAOS=$RUN_CHAOS CHAOS_APPROVED=$CHAOS_APPROVED. Destructive chaos requires explicit opt-in and backup/recovery checks."
fi

# 10. Generate report
OUT_DIR="$OUT_DIR" STATUS_FILE="$STATUS_FILE" REPORT_FILE="$REPORT_FILE" python3 - <<'PY'
import os
from pathlib import Path
from collections import defaultdict
out=Path(os.environ['OUT_DIR'])
status=Path(os.environ['STATUS_FILE'])
rows=[]
if status.exists():
    for line in status.read_text().splitlines():
        parts=line.split('\t')
        while len(parts)<5: parts.append('')
        rows.append(parts[:5])
by=defaultdict(lambda: defaultdict(int))
for d,s,n,e,note in rows:
    by[d][s]+=1
p0_fail=sum(1 for d,s,_,_,_ in rows if s=='FAIL' and d.split('-',1)[0] in {'01','02','03','04','05'})
any_fail=sum(1 for _,s,_,_,_ in rows if s=='FAIL')
blocked=sum(1 for _,s,_,_,_ in rows if s in {'BLOCKED','DEFERRED'})
smtp_deferred=any('smtp' in n.lower() and s=='DEFERRED' for _,s,n,_,_ in rows)
if p0_fail:
    sandbox='FAIL'
elif any(s=='FAIL' for d,s,_,_,_ in rows if d.startswith(('00','01','02','03','05','08'))):
    sandbox='PARTIAL'
else:
    sandbox='PASS'
supervised='FAIL' if p0_fail else ('PARTIAL' if any_fail or blocked else 'PASS')
customer='PARTIAL' if smtp_deferred else supervised
production='PARTIAL' if smtp_deferred or any_fail or blocked else 'PASS'
lines=[]
lines.append('# AMINRA Customer-Ready Full-System QA Report')
lines.append('')
lines.append(f'Generated: {__import__("datetime").datetime.now().isoformat()}')
lines.append(f'Output: `{out}`')
lines.append('')
lines.append('## Verdict lanes')
lines.append('')
lines.append(f'- sandbox_demo: **{sandbox}**')
lines.append(f'- supervised_pilot: **{supervised}**')
lines.append(f'- customer_onboarding: **{customer}** — SMTP deferred prevents PASS when deferred.')
lines.append(f'- production_go: **{production}** — requires SMTP, zero dirty release boundary, accepted load/chaos/deploy gates.')
lines.append('')
lines.append('## Summary by domain')
lines.append('')
for d in sorted(by):
    counts=', '.join(f'{k}={v}' for k,v in sorted(by[d].items()))
    lines.append(f'- {d}: {counts}')
lines.append('')
lines.append('## Detailed results')
lines.append('')
for d,s,n,e,note in rows:
    note_part=f' — {note}' if note else ''
    lines.append(f'- **{s}** `{d}` — {n}: `{e}`{note_part}')
lines.append('')
lines.append('## Required interpretation')
lines.append('')
lines.append('- `DEFERRED` is not a pass. SMTP/verifyEmail remains a customer-onboarding blocker until explicitly tested.')
lines.append('- Missing P0 lifecycle test files are blockers unless equivalent coverage is mapped with evidence.')
lines.append('- Any FAIL in auth, tenant, supply-chain, lifecycle, or admin identity domains is release-blocking.')
lines.append('- QA-created data cleanup must be verified in the relevant evidence logs before using this report for sign-off.')
Path(os.environ['REPORT_FILE']).write_text('\n'.join(lines)+'\n')
print(Path(os.environ['REPORT_FILE']))
PY

echo
cat "$REPORT_FILE"
echo
echo "Evidence root: $OUT_DIR"
echo "Status TSV: $STATUS_FILE"

# Exit non-zero when there are failures. Deferred/blocked remain visible but do not force shell failure.
if awk -F '\t' '$2=="FAIL" {found=1} END {exit found?0:1}' "$STATUS_FILE"; then
  exit 1
fi
exit 0
